# Production-only configuration
name = "pebble"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-24"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "PEBBLE_SYNC_KV"
id = "9fc443f3a8d2400399a31c800af3770d"

# Enable observability logs
[observability.logs]
enabled = true
