name = "pebble"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-24"

[[kv_namespaces]]
binding = "PEBBLE_SYNC_KV"
id = "1645f24f4fab4077b489234dc31da874"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true