name = "capture"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-24"

[[kv_namespaces]]
binding = "PEBBLE_SYNC_KV"
id = "8d1dfdac670a438a833da211262bcb90"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true