name = "pebble"
main = ".svelte-kit/cloudflare/_worker.js"

[kv_namespaces]
binding = "PEBBLE_SYNC_KV"
id = "your-kv-namespace-id"  # Replace with actual KV namespace ID

[secrets]
MASTER_HMAC_SECRET = "your-master-secret"  # Set via wrangler secret put