# Production-only configuration
name = "pebbledemo"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-24"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "pebble-demo"
id = "f14e7f4a57114c569fd710cf48398043"

# Enable observability logs
[observability.logs]
enabled = true
